version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: src/Dockerfile
    container_name: fastapi_src_app
    ports:
      - "8312:8312"
    volumes:
      - ./src:/app/src
    environment:
      - PYTHONUNBUFFERED=1

  event_handler:
    build:
      context: .
      dockerfile: event_handler/Dockerfile
    container_name: fastapi_event_handler_app
    ports:
      - "8313:8313"
    volumes:
      - ./event_handler:/app/event_handler
    environment:
      - PYTHONUNBUFFERED=1
